export const FETCH_EMPLOYERS = "FETCH_EMPLOYERS";

export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";

export const FETCH_WORKINGMONTHS = "FETCH_WORKINGMONTHS";

export const FETCH_DEPARTMENTS_MANAGEMENT = "FETCH_DEPARTMENTS_MANAGEMENT";